USE ecommerce;

INSERT INTO products (name, img_link, price, description) VALUES
('Blue Diamond Almonds Lightly Salted', '/assets/img/almonds.png', 238.85, 'Blue Diamond Almonds Lightly Salted offer a deliciously satisfying crunch with a light touch of salt. These premium almonds are perfect for snacking or adding a nutritious touch to your recipes. They are roasted to perfection, ensuring a crispy texture and a rich, nutty flavor that enhances any dish. Enjoy them as a quick snack or as an ingredient in your favorite dishes. Each package is carefully sealed to preserve freshness and quality. Ideal for those who love a healthy, flavorful treat.'),
  
('Fresh organic apple 1kg simla grande', '/assets/img/apple.png', 17.85, 'Enjoy the crisp and juicy taste of fresh organic apples from Simla. These apples are grown without synthetic pesticides or fertilizers, ensuring a pure and natural flavor. Perfect for snacking, baking, or adding to salads, these apples provide a sweet and refreshing taste with every bite. Each apple is carefully selected for its quality and flavor, making them a great choice for health-conscious individuals who appreciate the taste of organically grown fruit. Packed with essential nutrients, these apples are a delicious way to stay healthy.'),
  
('Blue Diamond Almonds Lightly Salted Vegetables', '/assets/img/cereal.png', 23.85, 'Blue Diamond Almonds Lightly Salted Vegetables combine the crunchy goodness of almonds with a subtle hint of salt, creating a savory snack experience. These almonds are lightly seasoned to enhance their natural flavor without overwhelming it. Ideal for a quick snack or as a flavorful addition to your dishes, these almonds offer a satisfying crunch and a burst of nutrition. Perfect for adding a touch of elegance to your culinary creations or enjoying straight from the package. They are roasted to perfection and sealed to maintain freshness.'),
  
('Gorton’s Beer Battered Fish Fillets with soft paper', '/assets/img/coffee.png', 23.85, 'Gorton’s Beer Battered Fish Fillets deliver a delightful taste of crispy, beer-battered fish with every bite. These fillets are coated in a light, crunchy batter made with real beer for a flavorful and satisfying crunch. Ideal for a quick meal or as a delicious addition to your family dinners, these fish fillets are easy to prepare and offer a taste of classic comfort food. Each fillet is perfectly seasoned and ready to be enjoyed with your favorite sides. Great for a tasty and convenient meal.'),
  
('Best snacks with hazel nut pack 200gm', '/assets/img/hazelnut.png', 52.85, 'Indulge in the rich, nutty flavor of our Best Snacks with Hazel Nut Pack. This 200-gram pack is filled with deliciously roasted hazelnuts, offering a crunchy texture and a satisfying taste. Perfect for snacking on the go or as an ingredient in your favorite recipes, these hazelnuts are a great source of essential nutrients and healthy fats. Each pack is carefully sealed to ensure freshness and maintain the quality of the nuts. Enjoy a wholesome and tasty treat with every handful.'),
  
('Haagen-Dazs Caramel Cone Ice Cream Ketchup', '/assets/img/icecream.png', 22.85, 'Haagen-Dazs Caramel Cone Ice Cream offers a luxurious dessert experience with its rich caramel flavor and crunchy cone pieces. This indulgent ice cream combines creamy caramel ice cream with bits of crispy cone, providing a delightful contrast in texture and taste. Perfect for a sweet treat or a special dessert, this ice cream is made with high-quality ingredients to deliver a smooth, satisfying flavor. Each scoop is a delicious combination of caramel and cone that will delight your taste buds. Enjoy the perfect blend of sweetness and crunch.'),
  
('Fresh organic villa farm lemon 500gm pack', '/assets/img/lemon.png', 28.85, 'Our Fresh Organic Villa Farm Lemons are grown without synthetic pesticides or fertilizers, ensuring a pure and zesty flavor. Each 500-gram pack contains vibrant, juicy lemons that are perfect for adding a tangy twist to your recipes or beverages. Ideal for cooking, baking, or making refreshing lemonade, these lemons offer a burst of citrusy freshness with every squeeze. Grown with care on our organic farm, these lemons are packed with essential vitamins and minerals, making them a healthy addition to your kitchen.'),
  
('Canada Dry Ginger Ale – 2 L Bottle - 200ml - 400g', '/assets/img/pistachio.png', 32.85, 'Canada Dry Ginger Ale is a refreshing beverage with a crisp, clean taste. The 2-liter bottle is perfect for sharing with friends and family or for enjoying on your own. This ginger ale offers a smooth and bubbly experience with just the right amount of ginger flavor, making it a great choice for pairing with meals or enjoying as a standalone drink. The convenient 200ml bottle size is ideal for on-the-go or for a quick refreshment. Experience the classic taste of Canada Dry Ginger Ale in every sip.'),
  
('Encore Seafoods Stuffed Alaskan Salmon', '/assets/img/salmon.png', 35.85, 'Encore Seafoods Stuffed Alaskan Salmon offers a gourmet dining experience with its rich, flavorful stuffing and high-quality salmon. Each piece is filled with a savory stuffing that complements the natural flavor of the Alaskan salmon, providing a delicious and satisfying meal. Perfect for special occasions or a fancy dinner at home, this stuffed salmon is easy to prepare and delivers a taste of luxury with every bite. Enjoy a taste of the sea with a touch of elegance and gourmet quality.'),
  
('Angie’s Boomchickapop Sweet and Salty', '/assets/img/snacks.png', 238.85, 'Angie’s Boomchickapop Sweet and Salty popcorn offers a delightful balance of sweet and savory flavors. This snack is perfect for those who love a crunchy treat with a touch of sweetness and a hint of salt. Made with high-quality ingredients and popped to perfection, this popcorn is an ideal choice for snacking at home or on the go. Each bag is filled with light and airy popcorn that’s sure to satisfy your cravings for a delicious and satisfying snack. Enjoy the perfect combination of sweet and salty flavors with every bite.'),
  
('Foster Farms Takeout Crispy Classic', '/assets/img/veggies.png', 238.85, 'Foster Farms Takeout Crispy Classic offers a delicious, crispy texture with every bite. These crispy classics are perfect for a quick and satisfying meal, delivering the taste of classic comfort food with the convenience of easy preparation. Ideal for busy days or family dinners, this product provides a crispy and flavorful experience that’s sure to please. Enjoy the crispy texture and rich flavor that make these classics a great choice for any meal. Quick, convenient, and delicious.'),
  
('Organic fresh villa farm watermelon 5kg', '/assets/img/watermelon.png', 48.85, 'Enjoy the refreshing taste of Organic Fresh Villa Farm Watermelon. This 5kg watermelon is grown without synthetic pesticides or fertilizers, ensuring a naturally sweet and juicy flavor. Perfect for summer picnics or as a hydrating snack, this watermelon is packed with essential nutrients and vitamins. Each slice offers a burst of freshness and a satisfying crunch, making it an ideal choice for a healthy and delicious treat. Enjoy the pure taste of organic watermelon in every bite.'),
  
('Chobani Complete Vanilla Greek Yogurt', '/assets/img/yogurt.png', 54.85, 'Chobani Complete Vanilla Greek Yogurt offers a rich, creamy texture and a delicious vanilla flavor. Made with high-quality ingredients, this yogurt provides a satisfying taste and a good source of protein. Perfect for breakfast, a snack, or as a topping for your favorite dishes, Chobani Complete Vanilla Greek Yogurt is a versatile and nutritious option. Each serving delivers a smooth and creamy experience with the added benefit of probiotics for digestive health. Enjoy the rich vanilla flavor in every spoonful.');